### ISSUE TITLE
Error: Can not request changes on your own pull request

### ISSUE THREAD

**Issue by smaranh** [MorrisonCole/pr-lint-action#265]
I get this error on my pull request linting. I am experimenting with your Github action in my repo.

```
HttpError: Unprocessable Entity: "Can not request changes on your own pull request"
    at /home/runner/work/_actions/morrisoncole/pr-lint-action/v1.6.0/webpack:/pr-lint-action/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This is what my yml file looks like,

```
name: PR linting

on: 
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:

  pr-lint:
    name: Verify title format
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.6.0
        with:
          title-regex: '^(BREAKING CHANGE|build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z ]+\))?: [\w ]+$'
          on-failed-regex-comment: >
            Pull request titles must follow [conventional commit](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#summary) formatting.
            #### Title regex
            `^(BREAKING CHANGE|build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z ]+\))?: [\w ]+$`
          repo-token: '${{ secrets.REPO_TOKEN }}'
```

Does the error mean to say that I cannot use this action on my own pull request?
