### ISSUE TITLE
Review comment on successful check (not as expected)

### ISSUE THREAD

**Issue by AirOnSkin** [MorrisonCole/pr-lint-action#355]
I'm not sure if I'm doing something wrong, but `on-failed-regex-create-review` suggests to me, that a review comment will only be created when the pr lint check fails. However, for me it creates a review with the message that it failed on successful checks:

![prlint](https://user-images.githubusercontent.com/3176649/181450245-d6b50cda-7c3d-410a-9c28-f261596b8320.png)

This is my workflow file:
```
---
name: Pull Request Lint
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pull-request-lint:
    runs-on: ubuntu-latest

    steps:
      # run linter
      - uses: morrisoncole/pr-lint-action@v1.6.1
        with:
          title-regex: '^(chore|doc|feat|fix|refactor|style)i\([A-Z]{2,4}\-\d{1,5}\)\:\ .{3,60}$'
          on-failed-regex-fail-action: false
          on-failed-regex-request-changes: false
          on-failed-regex-create-review: true
          on-failed-regex-comment:
            "Pull request title doesn't match contributing guidelines. See: [CONTRIBUTING.md](https://github.com/someorg/somerepo/blob/main/.github/CONTRIBUTING.md)"
          on-succeeded-regex-dismiss-review-comment:
            "All good now :+1"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```
