### ISSUE TITLE
Workflow permissions on protected branches

### ISSUE THREAD

**Issue by Gakk** [MorrisonCole/pr-lint-action#371]
This action has worked great for us in the past, but after adding some branch protection rules it now fails with:

```
HttpError: Branch protections do not permit dismissing this review
    at /home/runner/work/_actions/morrisoncole/pr-lint-action/v1.6.1/webpack:/pr-lint-action/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Our **GITHUB_TOKEN** Permissions are:
```
  Checks: write
  Issues: write
  Metadata: read
  PullRequests: write
```

I am running your action with the following setup:

```
Run morrisoncole/pr-lint-action@v1.6.1
with:
    title-regex: ([A-Z]{2,5}-[0-9]{2,5}: .{3,})|(Bump .{3,})|(Workflow: .{3,})
    on-failed-regex-fail-action: false
    on-failed-regex-request-changes: true
    on-failed-regex-create-review: true
    on-failed-regex-comment: Title should start with JIRA issue, followed by colon, space and title.
    on-succeeded-regex-dismiss-review-comment: Thanks, pull request title is now well formed 👍
    repo-token: ***
```

I see that on [GitHub's documentation for the Reviews API](https://docs.github.com/en/rest/pulls/reviews#dismiss-a-review-for-a-pull-request) it says

> **Note:** To dismiss a pull request review on a protected branch, you must be a repository administrator or be included in the list of people or teams who can dismiss pull request reviews.

Does this mean that the normal `GITHUB_TOKEN` can not be used, and that I need to create a separate token to use with your action?
