### ISSUE TITLE
dismiss-review option does not work for custom tokens

### ISSUE THREAD

**Issue by AngryMaciek** [MorrisonCole/pr-lint-action#579]
I have the following CI job:

```YAML
  conventional-title:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.7.0
        with:
          repo-token: "${{ secrets.BOT_TOKEN }}"
          title-regex: "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore): .{1,}"
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-request-changes: true
          on-failed-regex-comment:
            "Please stick to Conventional Commits syntax for PR titles ;)"
          on-succeeded-regex-dismiss-review-comment:
            "Thank you <3"
```

Everything works fine if I use `GITHUB_TOKEN`.  

However, when I created a bot user dedicated to our project, created a PAT for it added it to the repo secrets and specified the ci job as above I only get notifications for `on-failed-regex-comment`. Whenever I edit/correct the PR title I do not get `on-succeeded-regex-dismiss-review-comment` text anymore :(
